[package]
name = "bitrix_actix_protobuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { workspace = true }
futures-util = { workspace = true }
derive_more = "0.99.5"
prost ="0.11"